#### This file contains requests to test the endpoints using VSCode's Rest Client

GET http://localhost:3000/garages

###

POST http://localhost:3000/garages
Content-Type: application/json

{
  "name": "Idumota",
  "leader": "Martin Chillout",
  "phone": "09061279158",
  "deadline": 17,
  "lat": -533,
  "lng": 51
}

###


GET http://localhost:3000/garages/5e5c4ee592d12e30440df204

###
DELETE http://localhost:3000/garages/5e5c4d06a017b91e2451d6b5

###
PATCH http://localhost:3000/garages/5e5cc8cb35c46c6180a1bb6d
Content-Type: application/json 

{
  "lng": 85
}