#### This file contains requests to test the endpoints using VSCode's Rest Client

################## Patient Routes ################
GET http://localhost:3000/patients

###

POST http://localhost:3000/patients
Content-Type: application/json

{
  "name": "Daniel Dante",
  "card": 93241,
  "category": "student",
  "contact": "08032177494",
  "address": "17, bbs road, babcock university",
  "id": 210202,
  "marital": "Single",
  "age": 29,
  "occupation": "Carpenter"
}

###


GET http://localhost:3000/patients/5e5e50dddb12b13798eb22a0

###
DELETE http://localhost:3000/patients/5e5e0b40a360871aa839c23e

###
PATCH http://localhost:3000/patients/5e5e6ea5aa43211294d3e1da
Content-Type: application/json 

{
  "name": "Wisdom Yombouno",
  "occupation": "Driver",
  "marital": "Divorced",
  "category": "nontstaff",
  "address": "7, Unity street, Cambridge, London",
  "height": 98,
  "pulse": 44,
  "respiratory": 89,
  "BMI": 56,
  "temperature": 32,
  "sugarlevel": 67,
  "bloodgroup": "O+",
  "allergies": "Money",
  "addictions": "Guys"
}
